<script>
    let instance = new Promise((resolv, reject) => {
        setTimeout(() => {
            const rand = Math.floor(Math.random() * 11);

            if (rand < 5) {
                reject(rand);
            } else {
                resolv(rand);
            }
        }, 1000);
    });

    instance = instance.then(value => {
        console.log(`5以上の値[${value}]が渡ってきました。`);
    });

    instance = instance.catch(errorValue => {
        console.log(`5未満の値[${errorValue}]が渡ってきたためエラー表示。`);
    });

    instance = instance.finally(() => {
        console.log("処理を終了します。");
    });
</script>